import type { DashboardOpenOrder, DashboardEndedOrder, LinkedWallet } from '../types';

// Profile data
export const profileData = {
  walletAddress: 'GQ98iA5YmBxKgeDS3pqFCY6oi7Z9wxEfviKQN7k6iA5Y',
  walletShort: 'GQ98...iA5Y',
  totalTradingVol: '$18.72K',
  discountTier: '-0% Fee',
  xWhalesHolding: 0.00,
  linkedWallets: [
    { address: '0x6...4cd', chain: 'ethereum', chainColor: '#627eea' },
    { address: 'GQ9...A5Y', chain: 'solana', chainColor: '#9945ff' },
    { address: 'sei...2m6', chain: 'sei', chainColor: '#9945ff' },
  ] as LinkedWallet[],
};

// Open Orders (28 total)
export const openOrders: DashboardOpenOrder[] = [
  {
    id: 'oo-1',
    pair: 'SKATE/SOL',
    tokenColor: '#eab308',
    createdTime: '1 min ago',
    side: 'Buy',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    toBeReceived: '1.00K',
    toBeReceivedType: 'token',
    progress: 76.9,
  },
  {
    id: 'oo-2',
    pair: 'SKATE/SOL',
    tokenColor: '#eab308',
    hasBadge: 'FULL',
    createdTime: '2 days ago',
    side: 'Sell',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    toBeReceived: '1.50',
    toBeReceivedType: 'sol',
    progress: 0,
  },
  {
    id: 'oo-3',
    pair: 'SKATE/SOL',
    tokenColor: '#eab308',
    createdTime: '2 days ago',
    side: 'Sell',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    toBeReceived: '1.50',
    toBeReceivedType: 'sol',
    progress: 0,
  },
  {
    id: 'oo-4',
    pair: 'SKATE/SOL',
    tokenColor: '#eab308',
    hasBadge: 'RS',
    createdTime: '1 week ago',
    side: 'Resell',
    price: 0.010,
    amount: '1.00K',
    deposited: '1.00',
    depositedType: 'sol',
    toBeReceived: '2.00',
    toBeReceivedType: 'sol',
    progress: 0,
  },
  {
    id: 'oo-5',
    pair: 'XPL/USDC',
    tokenColor: '#16c284',
    createdTime: '1 min ago',
    side: 'Buy',
    price: 0.29,
    amount: '15.50K',
    deposited: '4.50K',
    depositedType: 'token',
    toBeReceived: '15.50K',
    toBeReceivedType: 'sol',
    progress: 0,
  },
  {
    id: 'oo-6',
    pair: 'PTB/SOL',
    tokenColor: '#fb923c',
    hasBadge: 'RS',
    createdTime: '1 week ago',
    side: 'Resell',
    price: 0.010,
    amount: '7.00K',
    deposited: '2.10',
    depositedType: 'sol',
    toBeReceived: '4.20',
    toBeReceivedType: 'sol',
    progress: 0,
  },
  // Generate more orders to reach 28 total
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `oo-${i + 7}`,
    pair: ['SKATE/SOL', 'PENGU/SOL', 'XPL/USDC', 'PTB/SOL'][i % 4],
    tokenColor: ['#eab308', '#3b82f6', '#16c284', '#fb923c'][i % 4],
    createdTime: `${i + 2} days ago`,
    side: (['Buy', 'Sell', 'Buy', 'Sell'] as const)[i % 4],
    price: [0.0050, 0.0050, 0.29, 0.010][i % 4],
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol' as const,
    toBeReceived: '1.50',
    toBeReceivedType: 'sol' as const,
    progress: 0,
  })),
];

// Filled Orders (132 total - reuse same structure)
export const filledOrders: DashboardOpenOrder[] = Array.from({ length: 132 }, (_, i) => ({
  id: `fo-${i + 1}`,
  pair: ['SKATE/SOL', 'PENGU/SOL', 'XPL/USDC', 'ME/SOL'][i % 4],
  tokenColor: ['#eab308', '#3b82f6', '#16c284', '#ec4899'][i % 4],
  hasBadge: (i % 5 === 0 ? 'RS' : undefined) as 'RS' | undefined,
  createdTime: `${Math.floor(i / 3) + 1} days ago`,
  side: (['Buy', 'Sell', 'Buy', 'Resell'] as const)[i % 4],
  price: 0.0050,
  amount: '1.00K',
  deposited: '1.50',
  depositedType: 'sol' as const,
  toBeReceived: '1.50',
  toBeReceivedType: 'sol' as const,
  progress: i % 3 === 0 ? 100 : i % 3 === 1 ? 76.9 : 50,
}));

// Ended orders (132 total)
export const endedOrders: DashboardEndedOrder[] = [
  {
    id: 'eo-1',
    pair: 'PENGU/SOL',
    tokenColor: '#3b82f6',
    time: '2 weeks ago',
    side: 'Buy',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '1.00K',
    receivedType: 'token',
    status: 'settled',
  },
  {
    id: 'eo-2',
    pair: 'ME/SOL',
    tokenColor: '#ec4899',
    time: '3 months ago',
    side: 'Buy',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '3.00',
    receivedType: 'sol',
    status: 'claimed',
  },
  {
    id: 'eo-3',
    pair: 'PENGU/SOL',
    tokenColor: '#3b82f6',
    time: '3 months ago',
    side: 'Buy',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '0.50',
    receivedType: 'sol',
    status: 'closed',
  },
  {
    id: 'eo-4',
    pair: 'MERL/SOL',
    tokenColor: '#06b6d4',
    hasBadge: 'RS',
    time: '1 year ago',
    side: 'Resell',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '2.00',
    receivedType: 'sol',
    status: 'resold',
  },
  {
    id: 'eo-5',
    pair: 'PENGU/SOL',
    tokenColor: '#3b82f6',
    hasBadge: 'RS',
    time: '1 year ago',
    side: 'Buy',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '1.00K',
    receivedType: 'token',
    status: 'settled',
  },
  {
    id: 'eo-6',
    pair: 'PENGU/SOL',
    tokenColor: '#3b82f6',
    hasBadge: 'RS',
    time: '1 year ago',
    side: 'Resell',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '0.00',
    receivedType: 'sol',
    status: 'claimed',
  },
  {
    id: 'eo-7',
    pair: 'PENGU/SOL',
    tokenColor: '#3b82f6',
    time: '1 year ago',
    side: 'Sell',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '3.00',
    receivedType: 'sol',
    status: 'settled',
  },
  {
    id: 'eo-8',
    pair: 'PENGU/SOL',
    tokenColor: '#3b82f6',
    time: '23/02/2024 15:33:15',
    side: 'Sell',
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol',
    received: '0.00',
    receivedType: 'sol',
    status: 'claimed',
  },
  // Generate more to reach 132
  ...Array.from({ length: 124 }, (_, i) => ({
    id: `eo-${i + 9}`,
    pair: ['PENGU/SOL', 'ME/SOL', 'SKATE/SOL', 'MERL/SOL'][i % 4],
    tokenColor: ['#3b82f6', '#ec4899', '#eab308', '#06b6d4'][i % 4],
    hasBadge: (i % 6 === 0 ? 'RS' : undefined) as 'RS' | undefined,
    time: `${Math.floor(i / 4) + 1} months ago`,
    side: (['Buy', 'Sell', 'Buy', 'Resell'] as const)[i % 4],
    price: 0.0050,
    amount: '1.00K',
    deposited: '1.50',
    depositedType: 'sol' as const,
    received: ['1.50', '3.00', '0.50', '2.00'][i % 4],
    receivedType: 'sol' as const,
    status: (['settled', 'claimed', 'closed', 'resold'] as const)[i % 4],
  })),
];
