import type { RecentTrade } from '../types';

export const recentTrades: RecentTrade[] = [
  {
    id: '1',
    time: '1m ago',
    side: 'Buy',
    hasBadge: 'RS',
    pair: 'IKA/USDT',
    pairIcon: '/tokens/ika.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.119,
    amount: '4.20K',
    collateral: 500.0,
    collateralIcon: '/tokens/usdt.svg',
    tierIcon: 'fish', // $500 → $100-$1K
  },
  {
    id: '2',
    time: '3m ago',
    side: 'Buy',
    hasBadge: 'RS',
    pair: 'PENGU/SOL',
    pairIcon: '/tokens/pengu.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '85.35K',
    collateral: 3.0,
    collateralIcon: '/tokens/sol.svg',
    tierIcon: 'fish', // ~$450 in SOL → $100-$1K
  },
  {
    id: '3',
    time: '5m ago',
    side: 'Buy',
    pair: 'GRASS/USDC',
    pairIcon: '/tokens/grass.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.069,
    amount: '3.62K',
    collateral: 250.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'fish', // $250 → $100-$1K
  },
  {
    id: '4',
    time: '8m ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '100.00K',
    collateral: 5000.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'dolphin', // $5K → $1K-$10K
  },
  {
    id: '5',
    time: '12m ago',
    side: 'Sell',
    pair: 'ZBT/USDC',
    pairIcon: '/tokens/zbt.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.055,
    amount: '18.18K',
    collateral: 15000.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shark', // $15K → $10K-$100K
  },
  {
    id: '6',
    time: '16m ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '40.00K',
    collateral: 200.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'fish', // $200 → $100-$1K
  },
  {
    id: '7',
    time: '22m ago',
    side: 'Sell',
    pair: 'LOUD/USDT',
    pairIcon: '/tokens/loud.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.9638,
    amount: '5.50K',
    collateral: 5300.0,
    collateralIcon: '/tokens/usdt.svg',
    tierIcon: 'dolphin', // $5.3K → $1K-$10K
  },
  {
    id: '8',
    time: '35m ago',
    side: 'Buy',
    pair: 'IKA/USDC',
    pairIcon: '/tokens/ika.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.112,
    amount: '8.92K',
    collateral: 150000.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'whale', // $150K → Over $100K
  },
  {
    id: '9',
    time: '42m ago',
    side: 'Buy',
    pair: 'PENGU/SOL',
    pairIcon: '/tokens/pengu.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.0048,
    amount: '62.50K',
    collateral: 50000.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shark', // $50K → $10K-$100K
  },
  {
    id: '10',
    time: '1h ago',
    side: 'Buy',
    pair: 'GRASS/USDC',
    pairIcon: '/tokens/grass.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.0613,
    amount: '3.62K',
    collateral: 50.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shrimp', // $50 → < $100
  },
];
