import type { RecentTrade } from '../types';

export const recentTrades: RecentTrade[] = [
  {
    id: '1',
    time: '1m ago',
    side: 'Sell',
    pair: 'Meteora/USDC',
    pairIcon: '/tokens/meteora.svg',
    pairChain: 'solana',
    market: 'Points',
    price: 0.055,
    amount: '3.64K',
    collateral: 200.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shark',
  },
  {
    id: '2',
    time: '5m ago',
    side: 'Sell',
    pair: 'Karad/USDC',
    pairIcon: '/tokens/karad.svg',
    pairChain: 'solana',
    market: 'Points',
    price: 0.055,
    amount: '18.18K',
    collateral: 1000.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'whale',
  },
  {
    id: '3',
    time: '9m ago',
    side: 'Buy',
    hasBadge: 'RS',
    pair: 'IKA/USDT',
    pairIcon: '/tokens/ika.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.119,
    amount: '4.20K',
    collateral: 500.0,
    collateralIcon: '/tokens/usdt.svg',
    tierIcon: 'shark',
  },
  {
    id: '4',
    time: '12m ago',
    side: 'Buy',
    hasBadge: 'RS',
    pair: 'PENGU/SOL',
    pairIcon: '/tokens/pengu.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '85.35K',
    collateral: 3.0,
    collateralIcon: '/tokens/sol.svg',
    tierIcon: 'shark',
  },
  {
    id: '5',
    time: '14m ago',
    side: 'Buy',
    pair: 'GRASS/USDC',
    pairIcon: '/tokens/grass.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.069,
    amount: '3.62K',
    collateral: 250.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shark',
  },
  {
    id: '6',
    time: '16m ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '100.00K',
    collateral: 500.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'whale',
  },
  {
    id: '7',
    time: '38m ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '40.00K',
    collateral: 200.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shark',
  },
  {
    id: '8',
    time: '42m ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.005,
    amount: '100.00K',
    collateral: 500.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'whale',
  },
  {
    id: '9',
    time: '1h ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.0613,
    amount: '3.62K',
    collateral: 0.08,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shrimp',
  },
  {
    id: '10',
    time: '1h ago',
    side: 'Buy',
    pair: 'SKATE/USDC',
    pairIcon: '/tokens/skate.svg',
    pairChain: 'solana',
    market: 'Pre-market',
    price: 0.0055,
    amount: '1.82K',
    collateral: 100.0,
    collateralIcon: '/tokens/usdc.svg',
    tierIcon: 'shrimp',
  },
];
